### ISSUE TITLE
您好，我在使用您所提供的歌曲本体创建tdb时出现了问题：我直接将owl文件的后缀改为nt，然后在使用loader命令行进行创建，但是报错。

### ISSUE THREAD

**Issue by 1254859753** [zhangtao-seu/Jay_KG#1]
09:55:56 INFO  loader     :: -- Start triples data phase
09:55:56 INFO  loader     :: ** Load empty triples table
09:55:56 INFO  loader     :: -- Start quads data phase
09:55:56 INFO  loader     :: ** Load empty quads table
09:55:56 INFO  loader     :: Load: C:\Users\zc\Downloads\songs.nt -- 2020/05/23 09:55:56 CST
09:55:56 ERROR riot       :: [line: 1, col: 7 ] Bad character in IRI (space): <?xml[space]...>
org.apache.jena.riot.RiotException: [line: 1, col: 7 ] Bad character in IRI (space): <?xml[space]...>
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:147)
        at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:148)
        at org.apache.jena.riot.lang.LangEngine.<init>(LangEngine.java:49)
        at org.apache.jena.riot.lang.LangBase.<init>(LangBase.java:32)
        at org.apache.jena.riot.lang.LangNTuple.<init>(LangNTuple.java:58)
        at org.apache.jena.riot.lang.LangNTriples.<init>(LangNTriples.java:43)
        at org.apache.jena.riot.lang.RiotParsers.createParserNTriples(RiotParsers.java:91)
        at org.apache.jena.riot.lang.RiotParsers.createParser(RiotParsers.java:61)
        at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:190)
        at org.apache.jena.riot.RDFParser.read(RDFParser.java:353)
        at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:322)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:296)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:540)
        at org.apache.jena.riot.RDFDataMgr.parseFromURI(RDFDataMgr.java:921)
        at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:711)
        at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:680)
        at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:668)
        at org.apache.jena.tdb.store.bulkloader.BulkLoader.loadQuads$(BulkLoader.java:151)
        at org.apache.jena.tdb.store.bulkloader.BulkLoader.loadDataset(BulkLoader.java:109)
        at org.apache.jena.tdb.TDBLoader.loadDataset$(TDBLoader.java:259)
        at org.apache.jena.tdb.TDBLoader.loadDataset(TDBLoader.java:185)
        at org.apache.jena.tdb.TDBLoader.load(TDBLoader.java:69)
        at tdb.tdbloader.loadQuads(tdbloader.java:156)
        at tdb.tdbloader.exec(tdbloader.java:108)
        at jena.cmd.CmdMain.mainMethod(CmdMain.java:92)
        at jena.cmd.CmdMain.mainRun(CmdMain.java:58)
        at jena.cmd.CmdMain.mainRun(CmdMain.java:45)
        at tdb.tdbloader.main(tdbloader.java:52)

请问您两个问题：
1.loader可以直接转换owl文件么？
2.如果不行的话，用什么生成nt文件呢

**Comment by keyjhk** [comment]
我也遇到了同样的问题

**Comment by lfb637** [comment]
> 我也遇到了同样的问题
你解决了吗

**Comment by wazngzihui** [comment]
我也遇到了同样的问题，有解决方法吗
